"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const follower_controller_1 = require("../controllers/follower.controller");
const router = (0, express_1.Router)();
exports.router = router;
router.get('/all/:id', follower_controller_1.getFollowers);
router.get('/followed/:id', follower_controller_1.getFolloweds);
router.get('/:id', follower_controller_1.getOneFollower);
router.get('/:followerId/:followedId', follower_controller_1.getFollowerRelational);
router.post('/', follower_controller_1.insertFollower);
router.put('/:id', follower_controller_1.updateFollower);
router.delete('/:id', follower_controller_1.deleteFollower);
